Fix github actions

diff --git a/.github/workflows/dev-build.yml b/.github/workflows/dev-build.yml
--- a/.github/workflows/dev-build.yml
+++ b/.github/workflows/dev-build.yml
@@ -134,26 +134,22 @@ jobs:
           registry: ${{ env.JFROG_REGISTRY }}
           username: ${{ secrets.MSK_JFROG_USERNAME }}
           password: ${{ secrets.MSK_JFROG_TOKEN }}
-      - name: Build Image for JFrog
+      - name: Build Image locally and load into Docker
         uses: docker/build-push-action@v5
         with:
           context: containers/${{ matrix.tags }}/
           file: containers/${{ matrix.tags }}/Dockerfile
-          platforms: linux/amd64,linux/arm64
+          platforms: linux/amd64
           tags: ${{ steps.docker_tag.outputs.tag }}
           cache-from: type=gha,scope=${{ steps.docker_repo_name.outputs.name }}-dev
           cache-to: type=gha,mode=max,scope=${{ steps.docker_repo_name.outputs.name }}-dev
           secrets: |
             MSK_JFROG_USERNAME=${{ secrets.MSK_JFROG_USERNAME }}
             MSK_JFROG_TOKEN=${{ secrets.MSK_JFROG_TOKEN }}
-          push: true
+          load: true
       - name: Validate image build metadata
         run: |
           python .github/workflows/scripts/validate_docker.py ${{ steps.docker_tag.outputs.tag }} .github/workflows/scripts/jsonschema/docker_image.json
-      - name: Verify multi-arch manifest
-        run: |
-          echo "Verifying multi-arch manifest for ${{ steps.docker_repo_name.outputs.name }}:${{ steps.docker_repo_version.outputs.version }}"
-          docker buildx imagetools inspect ${{ steps.docker_tag.outputs.tag }} || echo "Develop Jfrog image verification failed"
       - name: Get privacy tag
         id: check_private
         run: |
@@ -166,6 +162,23 @@ jobs:
         id: privacy_message
         if: steps.check_private.outputs.private_image == 'true'
         run: echo "This image is private"
+      - name: Push Image to JFrog
+        uses: docker/build-push-action@v5
+        with:
+          context: containers/${{ matrix.tags }}/
+          file: containers/${{ matrix.tags }}/Dockerfile
+          platforms: linux/amd64,linux/arm64
+          tags: ${{ steps.docker_tag.outputs.tag }}
+          cache-from: type=gha,scope=${{ steps.docker_repo_name.outputs.name }}-dev
+          cache-to: type=gha,mode=max,scope=${{ steps.docker_repo_name.outputs.name }}-dev
+          secrets: |
+            MSK_JFROG_USERNAME=${{ secrets.MSK_JFROG_USERNAME }}
+            MSK_JFROG_TOKEN=${{ secrets.MSK_JFROG_TOKEN }}
+          push: true
+      - name: Verify multi-arch manifest
+        run: |
+          echo "Verifying multi-arch manifest for ${{ steps.docker_repo_name.outputs.name }}:${{ steps.docker_repo_version.outputs.version }}"
+          docker buildx imagetools inspect ${{ steps.docker_tag.outputs.tag }} || echo "Develop Jfrog image verification failed"
   confirm-pass:
     runs-on: ubuntu-latest
     needs: [dockerfile-changes, docker-validate-build-and-push, dockerfile-lint]
